Update URL API
TimeForANinja/node-ytpl pull request #111
Opened 2021-04-06 02:57 UTC by Progitiel

Move from deprecated Legacy API to WHATWG URL API.
[https://nodejs.org/api/url.html#url_legacy_url_api](url)

2021-04-10 20:23 UTC, TimeForANinja reviewed
Hey,
first of all thanks for the PR.
I'm fine with discussing adding support for RD-Playlists but for now i'd be happy keeping the two `.startsWith('RD')` statements out of this PR to merge it fast 😉

2021-04-11 19:41 UTC, Progitiel commented
I agree. With this goal in mind, the two `.startsWith('RD')` don't need to be added.

2021-04-24 21:25 UTC, TimeForANinja requested changes
Hey
would be cool if we can get this done 😉

2021-04-24 21:25 UTC, TimeForANinja commented on lib/main.js
> +  if (PLAYLIST_REGEX.test(linkOrId) || ALBUM_REGEX.test(linkOrId) || linkOrId.startsWith('RD')) {
```suggestion
  if (PLAYLIST_REGEX.test(linkOrId) || ALBUM_REGEX.test(linkOrId)) {
```

2021-04-24 21:25 UTC, TimeForANinja commented on lib/main.js
> +  if (PLAYLIST_REGEX.test(linkOrId) || ALBUM_REGEX.test(linkOrId) || linkOrId.startsWith('RD')) {
```suggestion
  if (PLAYLIST_REGEX.test(linkOrId) || ALBUM_REGEX.test(linkOrId)) {
```

2021-04-25 23:44 UTC, merged

2021-04-25 23:44 UTC, TimeForANinja commented
👍 Thanks again for this PR
gonna push to npm in a sec